<footer class="footer">
    <div class="container">
        <div class="row m-5">
            <div class="col">
                <img src="/img/sprites/bike_white.png"/>
                <img src="/img/sprites/bike_white.png"/>
            </div>
            <div class="col text-right">CREDIT <span id="credit">00</span></div>
            <!-- <div class="col text-right"><a href="\credit" class="pull-right">CREDIT 01</a></div> -->
        </div>
    </div>
</footer>
