<div class="navbar">
    <div class="container d-flex justify-content-between">
      <!-- <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>CYCLE SPACE<br>INVADERS</strong>
      </a> -->
      <a class="nav-button ml-auto mr-4"><span id="nav-icon3"><span></span><span></span><span></span><span></span></span></a>
    </div>
  </div> <!--navbar end-->

  <div class="fixed-top main-menu">
    <div class="flex-center p-5">
      <ul class="nav flex-column">
        <li class="nav-item delay-1"><a class="nav-link  red" href="/">HOME</a></li>
        <li class="nav-item delay-2"><a class="nav-link purple" href="/leader-board">LEADER BOARD</a></li>
        <li class="nav-item delay-3"><a class="nav-link " href="/invaders">INVADERS</a></li>
        <li class="nav-item delay-4"><a class="nav-link light-blue" href="/players">PLAYERS</a></li>
        <li class="nav-item delay-5"><a class="nav-link yellow blink" href="/get-involved">INSERT COIN</a></li>
      </ul>
    </div>
  </div> <!--main-menu end-->
