<div class="container score_advance my-5">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1 class="mb-4">* SCORE ADVANCE TABLE *</h1>

            <div class="accordion" id="accordionExample">

                <div class="" id="headingOne">
                    <h2 class="mb-0">
                        <button class="btn btn-link purple" type="button" data-toggle="collapse"
                                data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                            <i class="fa fa-car"></i> = 10 POINTS
                        </button>
                    </h2>
                </div>

                <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
                    <div class="my-3">
                        Capture an photo or video of an invader in a cyclelane for 10 points.
                    </div>
                </div>

                <div class="">
                    <div class="" id="headingTwo">
                        <h2 class="mb-0">
                            <button class="btn btn-link collapsed green" type="button" data-toggle="collapse"
                                    data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                                <i class="fa fa-map-marker"></i> = 05 POINTS
                            </button>
                        </h2>
                    </div>
                    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                        <div class="my-3">
                            Geotag your tweet for an additional 5 points.<br>
                            This will help to map and identify hotspots.
                        </div>
                    </div>
                </div>

                <div class="">
                    <div class="" id="headingThree">
                        <h2 class="mb-0">
                            <button class="btn btn-link collapsed yellow" type="button" data-toggle="collapse"
                                    data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                                # = 05 POINTS
                            </button>
                        </h2>
                    </div>
                    <div id="collapseThree" class="collapse" aria-labelledby="headingThree"
                         data-parent="#accordionExample">
                        <div class="my-3">
                            Add your town, city or county as a hashtag for an additional 5 points.<br>
                            This will help to group issues for a locality.
                        </div>
                    </div>
                </div>

                <div class="">
                    <div class="" id="headingFour">
                        <h2 class="mb-0">
                            <button class="btn btn-link collapsed red" type="button" data-toggle="collapse"
                                    data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
                                ? = 03 POINTS
                            </button>
                        </h2>
                    </div>
                    <div id="collapseFour" class="collapse" aria-labelledby="headingFour"
                         data-parent="#accordionExample">
                        <div class="my-3">
                            You will have to figure this one out :)
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
