<div class="card p-1">
    <a href="/invader/<?= $v($tweet['id']) ?>" class="item">
        <!-- <img class="card-img-top img-fluid" src="..." alt="Card image cap"> -->

        <?php if ($tweet['media']):
            $media = JSON_decode($tweet['media']);
            ?>

            <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner">

                    <?php
                    $flag = true;
                    foreach ($media as $m):?>
                        <div class="carousel-item <?php echo $flag ? ' active' : ''; ?>">
                            <img class="d-block w-100" src="<?= $v($m->media_url_https) ?>" alt="First slide">
                        </div>

                        <?php $flag = false;
                    endforeach; ?>

                </div>
            </div>


        <?php endif; ?>

        <div class="card-block pt-2">
            <div class="row">
                <?php if (isset($tweet["avatar"])): ?>
                    <div class="col-2">
                        <img src="<?= $v($tweet["avatar"]) ?>" alt="" class="mx-auto img-fluid avatar" data-pixelate
                             data-reveal="false" data-value="0.4">
                    </div>
                <?php endif; ?>
                <div class="col-10 light-blue">
                    <?php if (isset($tweet["username"])): ?>
                        <h6 class="yellow mb-0">@<?= $v($tweet["username"]) ?></h6>
                    <?php endif; ?>
                    <?= $v(Carbon\Carbon::parse($tweet['created_at'])->format('d/m/y')) ?>
                </div>

            </div>
            <p class="card-text"><?= $v($tweet['text']) ?></p>
        </div>
    </a>
</div>
