<?php $v->layout('layout') ?>

<div class="container home">

    <div class="row">
        <div class="col-lg-12 text-center">
            <img src="\img\logo.png" class="mb-5 mx-auto img-fluid">
        </div>

        <div class="col-lg-12 text-center">
            <p class="lead">
                It is the year 2020 and Cycle Space has been INVADED.
            </p>
            <p class="lead">
                The traditional defenders of Cycle Space have been rendered inactive by the crippling GDPR virus
                (although experts think it might just be their imagination), so it falls to you to tackle these evil
                invaders, have you got what it takes to
                join the resistance ?<br>
                <br>
                In order to join, all you have to do is to capture these invaders by posting a photo or video of them to Twitter using the hashtag <span class="hilight yellow">#FreeTheCycleLanes</span> or <span class="hilight yellow">#KissTheGatesGoodbye</span>.
            </p>

            <h2 class="red blink my-4">
                ** Warning **
            </h2>
            <p class="lead">
                This is not a game, peoples lives are at risk !
            </p>

        </div>
    </div>

    <?php $v->insert('includes::score_table') ?>

    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">

                <h1 class="mb-5 purple">* RECENT INVADERS *</h1>

                <div class="card-columns text-left">

                    <?php foreach ($tweets as $tweet): ?>

                        <div class="card p-1">
                            <a href="/invader/<?= $v($tweet['id']) ?>" class="item">
                                <!-- <img class="card-img-top img-fluid" src="..." alt="Card image cap"> -->

                                <?php if ($tweet['media']):
                                    $media = JSON_decode($tweet['media']);
                                    ?>

                                    <div id="carouselExampleSlidesOnly" class="carousel slide" data-ride="carousel">
                                        <div class="carousel-inner">

                                            <?php
                                            $flag = true;
                                            foreach ($media as $m):?>
                                                <div class="carousel-item <?php echo $flag ? ' active' : ''; ?>">
                                                    <img class="d-block w-100" src="<?= $v($m->media_url_https) ?>"
                                                         alt="First slide">
                                                </div>

                                                <?php $flag = false;
                                            endforeach; ?>

                                        </div>
                                    </div>

                                <?php endif; ?>

                                <div class="card-block pt-2">
                                    <div class="row">

                                        <div class="col-2">
                                            <img src="<?= $v($tweet["avatar"]) ?>" alt=""
                                                 class="mx-auto img-fluid avatar" data-pixelate data-reveal="false"
                                                 data-value="0.4">
                                        </div>
                                        <div class="col-10 light-blue">
                                            <h6 class="yellow mb-0">@
                                                <?= $v($tweet["username"]) ?>
                                            </h6>
                                            <?= $v(Carbon\Carbon::parse($tweet['created_at'])->format('d/m/y')) ?>
                                        </div>

                                    </div>
                                    <p class="card-text">
                                        <?= $v($tweet['text']) ?>
                                    </p>
                                </div>
                            </a>
                        </div>

                    <?php endforeach; ?>

                </div>

                <h3 class="my-4">
                    <a href="/invaders">
                        << VIEW <?= $v($total_invaders) ?> INVADERS >>
                    </a>
                </h3>

                <img src="/img/game_shot.png" class="my-5 mx-auto img-fluid"/>

                <h1 class="my-4 purple">* PLAYERS *</h1>

                <div class="container players">

                    <div class="row">

                        <?php foreach ($players as $player): ?>

                            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 box">
                                <a href="/player/@<?= $v($player["username"]) ?>" class="">

                                    <div class="my-2">
                                        <img class="mx-auto" src="<?= $v(largeAvatar($player["avatar"])) ?>"
                                             data-pixelate data-reveal="false" data-value="0.2"/>
                                    </div>
                                    <div>
                                        @<?= $v($player["username"]) ?>
                                    </div>
                                    <div class="location">
                                        <?= $v($player["location"]) ?>
                                    </div>
                                </a>

                            </div>

                        <?php endforeach ?>

                    </div>

                </div>

                <h3 class="m-4"><a href="/players">
                        << VIEW ALL <?= $v($total_players) ?> PLAYERS >>
                    </a></h3>

            </div>
        </div>
    </div>


    <div class="container leaderboard">

        <div class="row">
            <div class="col-lg-12 text-center">
                <h1 class="my-4 red">*** Hi Score ***</h1>

                <table class="h4 m-5">
                    <thead>
                    <tr>
                        <th scope="col">RANK</th>
                        <th scope="col">NAME</th>
                        <th scope="col">SCORE</th>
                    </tr>
                    </thead>
                    <tbody>

                    <?php
                    $i = 1;
                    foreach ($leaders as $user): ?>
                        <tr>
                            <td scope="row"><?= $v($i) ?></td>
                            <td>
                                <a href="/player/@<?= $v($user["username"]) ?>">
                                    <!-- <img class="mx-auto rounded-circle img-fluid" src="<?= $v($user["avatar"]) ?>" width="50px"/>-->
                                    @<?= $v($user["username"]) ?>
                                </a>
                            </td>
                            <td><?= $v($user["total_score"]) ?></td>
                            <td></td>
                        </tr>

                        <?php
                        $i++;
                    endforeach ?>

                    </tbody>
                </table>

            </div>
        </div>
    </div>


    <?php $v->insert('includes::game_credits') ?>

    <?php $v->push('scripts') ?>
    <script>
        // Some JavaScript
    </script>
    <?php $v->end() ?>
