<?php $v->layout('layout') ?>
<div class="container invaders">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1 class="mt-5 mb-4 yellow">*** <span class="blink"><?= $v($total) ?></span> INVADERS *** </h1>

        </div>

    </div>

    <div class="row">

        <div class="card-columns">

            <?php
            foreach ($tweets as $tweet) {
                $v->insert('includes::tweet', ['tweet' => $tweet]);
            }
            ?>

        </div>

    </div>

    <div class="col-12 text-center my-5">
        <?php
        if ($total_pages > 1) {
            echo generatePageLinks($page, $total_pages, '/invaders/tag/' . $tag);
        }
        ?>
    </div>


    <?php $v->push('scripts') ?>
    <script>

    </script>
    <?php $v->end() ?>
