<?php $v->layout('layout', ['title' => 'Invader captured by @' . $data['username']]) ?>

<div class="container invader">
    <div class="row">
        <div class="col-12 text-center">
            <h1 class="mt-5 red ">*** INVADER ***</h1>
            <h2 class=" mb-4 yellow">#<?= $v($data['id']) ?></h2>

        </div>


        <!-- <div class="col-lg-4 col-sm-12">
      <h6>CAPTURED BY</h6>
      <h3 class="red"><a href="/player/@<?= $v($data['username']) ?>">@<?= $v($data['username']) ?></a></h3>


    </div>
     <div class="col-lg-4 col-sm-6">
       <h6>DATE CAPTURED</h6>
<h3 class="yellow"><?= $v(Carbon\Carbon::parse($data['created_at'])->format('d/m/y')) ?></h3>


            </div>
    <div class="col-lg-4 col-sm-6">
            <h6>TIME CAPTURED</h6>
      <h3 class="yellow"><?= $v(Carbon\Carbon::parse($data['created_at'])->format('h:m')) ?></h3>
    </div> -->


    </div>


    <div class="row">

        <div class="col-lg-4">

            <img src="<?= $v(largeAvatar($data["avatar"])) ?>" alt="" class="mx-auto img-fluid avatar" data-pixelate
                 data-reveal="false" data-value="0.2">
            <div class="my-5 text-right">
                <br>
                <h4 class="green"><a href="/player/@<?= $v($data['username']) ?>">@<?= $v($data['username']) ?></a></h4>
                <h4>CAPTURED BY</h4>
                <br>
                <h2 class="red"><?= $v($data['score']) ?></h2>
                <h4>SCORE</h4>
                <br>
                <h2 class="yellow"><?= $v(Carbon\Carbon::parse($data['created_at'])->format('d/m/y')) ?></h2>
                <h4>DATE</h4>
                <br>

                <h2 class="light-blue"><?= $v(Carbon\Carbon::parse($data['created_at'])->format('H:m')) ?></h2>
                <h4>TIME</h4>
                <br>

                <?php
                foreach (JSON_decode($data['hashtags']) as $tag):
                    if (strtolower($tag) !== strtolower($_ENV['HASHTAG'])):?>

                        <h5 class="red"><a href="/tag/<?= $v($tag) ?>">#<?= $v($tag) ?></a></h5>
                    <?php endif;
                endforeach; ?>
                <h4>TAGS</h4>

            </div>
        </div>

        <div class="col-lg-8 text-left">

            <div class="col-lg-12 text-center mb-5">
                <?php

                $media = JSON_decode($data['media']);

                foreach ($media as $m):
                    switch ($m->type) {
                        case 'photo':
                            echo '<img src="' . $m->media_url_https . '" class="mx-auto img-fluid "/>';
                            break;
                        case 'video':

                            echo '<video controls>
                        <source src="' . $m->video_info->variants[2]->url . '" type="' . $m->video_info->variants[2]->content_type . '">
                        <p>Your browser doesn\'t support HTML5 video.</p>
                      </video>';

                            break;

                        default:
                            # code...
                            break;
                    }

                endforeach;
                ?>

            </div>


            <!--
      <h1 class="  red ">*** INVADER ***</h1>
      <h2 class=" mb-4 yellow">#<?= $v($data['id']) ?></h2> -->

            <p class="lead">
                <?= $v(linkify($data['text'])) ?>
            </p>

            <h6 class="my-5">
                <?= $v(t_like($data['id'])) ?> | <?= $v(t_retweet($data['id'])) ?> | <?= $v(t_reply($data['id'])) ?>
                | <?= $v(t_link_tweet($data['id'])) ?>
                <h6>

        </div>

    </div>

</div>

</div>


<?php $v->push('scripts') ?>
<script>
    // Some JavaScript
</script>
<?php $v->end() ?>
