<?php $v->layout('layout') ?>

<div class="container player">

    <div class="row mt-5">
        <div class="col-lg-3">
            <img src="<?= $v(largeAvatar($user["avatar"])) ?>" alt="" class="mx-auto img-fluid avatar" data-pixelate
                 data-reveal="false" data-value="0.2">
            <div class="my-4 text-right">
                <h1 class="red"><?= $v($score) ?></h1>
                <h4>SCORE</h4>
                <br>
                <h1 class="purple"><?= $v($total) ?></h1>
                <h4>Invaders Captured</h4>
                <br>
                <!-- <h1 class="red"></h1>
                <h4>RANK</h4>
                <br> -->
                <h3 class="yellow"><?= $v(Carbon\Carbon::parse($user['created_at'])->format('d/m/y')) ?></h3>
                <h6>JOINED</h6>
                <br>
                <h3 class="light-blue"><?= $v(Carbon\Carbon::parse($last_active)->format('d/m/y')) ?></h3>
                <h6>LAST ACTIVE</h6>
                <br>
                <a href="/players">
                    <h4 class="green"><< ALL PLAYERS</h4>
                </a>

            </div>
        </div>

        <div class="col-lg-9 text-left">
            <h2 class=" my-2 yellow"><?= $v($user['screenname']) ?></h2>
            <h1 class=" red display-4">@<?= $v($user['username']) ?></h1>

            <?php
            if ($user["location"]) {
                ?>
                <span class="badge badge-info tags mb-2"><?= $v($user["location"]) ?></span>
                <?php
            } ?>

            <p class="description">
                <?= $v(linkify($user['description'])) ?>
            </p>

            <?php $url = 'https://cyclespaceinvaders.com/player/@' . $user['username'];// "//{$_SERVER['HTTP_HOST']}{$_SERVER['REQUEST_URI']}";?>

            <div>
                <?= $v(t_follow($user["id"])) ?>
                <span class="red">|</span>
                <a href="https://twitter.com/intent/tweet?text=<?= $v($user['screenname']) ?> is helping to Free The Cycle Lanes&url=<?= $v($url) ?>&hashtags=FreeTheCycleLanes,CycleSpaceInvaders&via=CycleInvaders&=related=TweetPhelan"
                   target="_BLANK">SHARE</a>
                <?php if ($user['url']): ?>
                    <span class="red">|</span>
                    <a href="<?= $v($user["url"]) ?>" target="_BLANK">WEBSITE</a>
                <?php endif; ?>
                <span class="red">|</span>
                <?= $v(t_link_user($user["username"])) ?>

            </div>

            <div class="row mt-4">
                <div class="col-12">

                    <div class="card-columns">

                        <?php
                        foreach ($tweets as $tweet) {
                            $v->insert('includes::tweet', ['tweet' => $tweet]);
                        }
                        ?>

                    </div>

                </div>

                <div class="col-12 text-center my-5">
                    <?php
                    if ($total_pages > 1) {
                        echo generatePageLinks((int)$page, (int)$total_pages, "/player/@" . $user['username'] . "/");
                    }
                    ?>
                </div>

            </div>

        </div>
    </div>
</div>


<?php $v->push('scripts') ?>

<script>
    // Some JavaScript
    $(function () {
        console.log("ready!");

        var myvalues = [10, 8, 5, 7, 4, 4, 1];
        $('.dynamicbar').sparkline(myvalues, {type: 'bar', barColor: 'green', barWidth: 20});

    });


</script>
<?php $v->end() ?>
