<?php $v->layout('layout', ['title' => 'Players']) ?>

<div class="container players">
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1 class="mt-5 mb-4">*** <span class="blink"><?= $v($total) ?></span> PLAYERS ***</h1>

            <!-- <ul class="nav justify-content-center">
        <li class="nav-item">
          <a class="nav-link<?php if ($mode == 'rookies'): ?> active<?php endif; ?>" href="/leader-board/">ROOKIES</a>
        </li>
        <li class="nav-item">
          <a class="nav-link<?php if ($mode == 'veterans'): ?> active<?php endif; ?>" href="/leader-board/veterans">VETERANS</a>
        </li>
      </ul> -->
            <br>
        </div>
    </div>


    <div class="row">

        <?php foreach ($players as $player): ?>


            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3 box">
                <a href="/player/@<?= $v($player["username"]) ?>" class="">

                    <div class="my-2">
                        <!-- <img class="mx-auto rounded-circle img-fluid" src="<?= $v(largeAvatar($player["avatar"])) ?>"> -->
                        <img class="mx-auto" src="<?= $v(largeAvatar($player["avatar"])) ?>" data-pixelate
                             data-reveal="false" data-value="0.2"/>
                    </div>
                    <div>
                        @<?= $v($player["username"]) ?>
                    </div>
                    <div class="location">
                        <?= $v($player["location"]) ?>
                    </div>
                </a>

            </div>


        <?php
        endforeach ?>


    </div>

</div>


</div>


<div class="row">


    <div class="col-12 text-center my-5">
        <?php
        if ($total_pages > 1) {
            echo generatePageLinks($page, $total_pages, '/players/');
        }
        ?>
    </div>

</div>

</div>
</div>

<?php $v->push('scripts') ?>
<script>
    // Some JavaScript
</script>
<?php $v->end() ?>
